In [1]:
import pandas as pd
import numpy as np

In [2]:
df=pd.read_csv('customer.csv')

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 33 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   CustomerID         7043 non-null   object
 1   Count              7043 non-null   int64
 2   Country            7043 non-null   object
 3   State              7043 non-null   object
 4   City               7043 non-null   object
 5   Zip Code           7043 non-null   int64
 6   Lat Long           7043 non-null   object
 7   Latitude           7043 non-null   float64
 8   Longitude          7043 non-null   float64
 9   Gender             7043 non-null   object
 10  Senior Citizen     7043 non-null   object
 11  Partner            7043 non-null   object
 12  Dependents         7043 non-null   object
 13  Tenure Months      7043 non-null   int64
 14  Phone Service      7043 non-null   object
 15  Multiple Lines     7043 non-null   object
 16  Internet Service   7043 non-null   object
 17  Online Security    7043 non-null   object
 18  Online Backup      7043 non-null   object
 19  Device Protection  7043 non-null   object
 20  Tech Support       7043 non-null   object
 21  Streaming TV       7043 non-null   object
 22  Streaming Movies   7043 non-null   object
 23  Contract           7043 non-null   object
 24  Paperless Billing  7043 non-null   object
 25  Payment Method     7043 non-null   object
 26  Monthly Charges    7043 non-null   float64
 27  Total Charges      7043 non-null   object
 28  Churn Label        7043 non-null   object
 29  Churn Value        7043 non-null   int64
 30  Churn Score        7043 non-null   int64
 31  CLTV               7043 non-null   int64
 32  Churn Reason       1869 non-null   object
dtypes: float64(3), int64(6), object(24)
memory usage: 1.8+ MB

In [4]:
df.isnull().sum()

CustomerID              0
Count                   0
Country                 0
State                   0
City                    0
Zip Code                0
Lat Long                0
Latitude                0
Longitude               0
Gender                  0
Senior Citizen          0
Partner                 0
Dependents              0
Tenure Months           0
Phone Service           0
Multiple Lines          0
Internet Service        0
Online Security         0
Online Backup           0
Device Protection       0
Tech Support            0
Streaming TV            0
Streaming Movies        0
Contract                0
Paperless Billing       0
Payment Method          0
Monthly Charges         0
Total Charges           0
Churn Label             0
Churn Value             0
Churn Score             0
CLTV                    0
Churn Reason         5174
dtype: int64

In [5]:
df["Country"].value_counts() # we will remove this column as there is only a unique country

Country
United States    7043
Name: count, dtype: int64

In [6]:
df["State"].value_counts()  # we will remove this column as there is only a unique state

State
California    7043
Name: count, dtype: int64

In [7]:
df["City"].value_counts()

City
Los Angeles       305
San Diego         150
San Jose          112
Sacramento        108
San Francisco     104
                 ...
Healdsburg          4
Jenner              4
Philo               4
Point Arena         4
Olympic Valley      4
Name: count, Length: 1129, dtype: int64

# Remove unnecessary columns and seperate input and output column

In [8]:
y = df["Churn Value"]

X = df.drop(columns=[
    "Churn Label",
    "Churn Value",
    "CustomerID",
    "Count",
    "Churn Score",
    "Churn Reason",
    "Country",
    "State"
])

In [9]:
X

,City,Zip Code,Lat Long,Latitude,Longitude,Gender,Senior Citizen,Partner,Dependents,Tenure Months,...,Device Protection,Tech Support,Streaming TV,Streaming Movies,Contract,Paperless Billing,Payment Method,Monthly Charges,Total Charges,CLTV
0,Los Angeles,90003,"33.964131, -118.272783",33.964131,-118.272783,Male,No,No,No,2,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,3239
1,Los Angeles,90005,"34.059281, -118.30742",34.059281,-118.307420,Female,No,No,Yes,2,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,2701
2,Los Angeles,90006,"34.048013, -118.293953",34.048013,-118.293953,Female,No,No,Yes,8,...,Yes,No,Yes,Yes,Month-to-month,Yes,Electronic check,99.65,820.5,5372
3,Los Angeles,90010,"34.062125, -118.315709",34.062125,-118.315709,Female,No,Yes,Yes,28,...,Yes,Yes,Yes,Yes,Month-to-month,Yes,Electronic check,104.80,3046.05,5003
4,Los Angeles,90015,"34.039224, -118.266293",34.039224,-118.266293,Male,No,No,Yes,49,...,Yes,No,Yes,Yes,Month-to-month,Yes,Bank transfer (automatic),103.70,5036.3,5340
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,Landers,92285,"34.341737, -116.539416",34.341737,-116.539416,Female,No,No,No,72,...,No internet service,No internet service,No internet service,No internet service,Two year,Yes,Bank transfer (automatic),21.15,1419.4,5306
7039,Adelanto,92301,"34.667815, -117.536183",34.667815,-117.536183,Male,No,Yes,Yes,24,...,Yes,Yes,Yes,Yes,One year,Yes,Mailed check,84.80,1990.5,2140
7040,Amboy,92304,"34.559882, -115.637164",34.559882,-115.637164,Female,No,Yes,Yes,72,...,Yes,No,Yes,Yes,One year,Yes,Credit card (automatic),103.20,7362.9,5560
7041,Angelus Oaks,92305,"34.1678, -116.86433",34.167800,-116.864330,Female,No,Yes,Yes,11,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.60,346.45,2793
7042,Apple Valley,92308,"34.424926, -117.184503",34.424926,-117.184503,Male,No,No,No,66,...,Yes,Yes,Yes,Yes,Two year,Yes,Bank transfer (automatic),105.65,6844.5,5097

In [10]:
X.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 25 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   City               7043 non-null   object
 1   Zip Code           7043 non-null   int64
 2   Lat Long           7043 non-null   object
 3   Latitude           7043 non-null   float64
 4   Longitude          7043 non-null   float64
 5   Gender             7043 non-null   object
 6   Senior Citizen     7043 non-null   object
 7   Partner            7043 non-null   object
 8   Dependents         7043 non-null   object
 9   Tenure Months      7043 non-null   int64
 10  Phone Service      7043 non-null   object
 11  Multiple Lines     7043 non-null   object
 12  Internet Service   7043 non-null   object
 13  Online Security    7043 non-null   object
 14  Online Backup      7043 non-null   object
 15  Device Protection  7043 non-null   object
 16  Tech Support       7043 non-null   object
 17  Streaming TV       7043 non-null   object
 18  Streaming Movies   7043 non-null   object
 19  Contract           7043 non-null   object
 20  Paperless Billing  7043 non-null   object
 21  Payment Method     7043 non-null   object
 22  Monthly Charges    7043 non-null   float64
 23  Total Charges      7043 non-null   object
 24  CLTV               7043 non-null   int64
dtypes: float64(3), int64(3), object(19)
memory usage: 1.3+ MB

In [11]:
X.describe()

,Zip Code,Latitude,Longitude,Tenure Months,Monthly Charges,CLTV
count,7043.000000,7043.000000,7043.000000,7043.000000,7043.000000,7043.000000
mean,93521.964646,36.282441,-119.798880,32.371149,64.761692,4400.295755
std,1865.794555,2.455723,2.157889,24.559481,30.090047,1183.057152
min,90001.000000,32.555828,-124.301372,0.000000,18.250000,2003.000000
25%,92102.000000,34.030915,-121.815412,9.000000,35.500000,3469.000000
50%,93552.000000,36.391777,-119.730885,29.000000,70.350000,4527.000000
75%,95351.000000,38.224869,-118.043237,55.000000,89.850000,5380.500000
max,96161.000000,41.962127,-114.192901,72.000000,118.750000,6500.000000